---
name: AmneziaWG Client
version: 0.1.0
slug: wireguard_client
description: AmneziaWG client for Home Assistant
url: https://github.com/nezg/addon-amnezia-wireguard-client
arch:
  - aarch64
  - amd64
  - armv7
init: false
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw

options:
  client:
    interface: wg0
    address: 10.9.1.18/32
    dns:
      - 1.1.1.1
      - 1.0.0.1
    private_key: ""

    jc: 5
    jmin: 10
    jmax: 50

    s1: 12
    s2: 12
    s3: 12
    s4: 12

    h1: 1
    h2: 2
    h3: 3
    h4: 4

    i1: ""
    header_protection_key: ""

    rekey_after_time: "100-120"
    rekey_timeout: "3-7"
    reject_after_time: "150-180"
    keepalive_timeout: "5-15"
    max_handshake_attempts: "15-20"

    random_trailers: true
    disable_cookies: true

    peer:
      public_key: ""
      preshared_key: ""
      allowed_ips:
        - 0.0.0.0/0
        - ::/0
      endpoint: "13.143.193.29:44736"
      persistent_keepalive: "25-35"

schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  client:
    interface: match(^wg([0-9])+$)?
    address: str
    dns:
      - str
    private_key: password?

    jc: int
    jmin: int
    jmax: int

    s1: int
    s2: int
    s3: int
    s4: int

    h1: int
    h2: int
    h3: int
    h4: int

    i1: str?
    header_protection_key: password?

    rekey_after_time: str?
    rekey_timeout: str?
    reject_after_time: str?
    keepalive_timeout: str?
    max_handshake_attempts: str?

    random_trailers: bool
    disable_cookies: bool

    peer:
      public_key: str
      preshared_key: password?
      allowed_ips:
        - str
      endpoint: str
      persistent_keepalive: str